Fixed Content-Lenght in the response
monstercat/s3-zipper pull request #2
Opened 2017-04-11 14:13 UTC by cab13140

This header is needed for download accelerators, and more commonly for all users to know the progress of the download

THIS THING NEEDS TESTING ! Not sure if it works, try it before merging

2017-04-11 16:36 UTC, tmathews requested changes
The reason you can't  do this method is because the archive is of unknown size as we are streaming the payload of the zipping process to the client.

2017-04-11 16:36 UTC, tmathews commented on src/index.js
> +    'Content-Lenght':filename.size
`filename` is a string. This won't work. `Content-Lenght` is misspelled.

2017-04-12 02:22 UTC, cab13140 commented on src/index.js
> +    'Content-Lenght':filename.size
How could I misspell length ?
I will find a way. But is the zipping process finished when the response is sent ?

2017-04-12 04:14 UTC, tmathews commented on src/index.js
> +    'Content-Lenght':filename.size
No, see line 77. We are piping the zipping process directly to the response stream.

2017-04-12 10:11 UTC, closed without merging

2017-04-12 10:12 UTC, cab13140 commented
Impossible ; See #3